// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PureLogicBackend.Data;

#nullable disable

namespace backend.Migrations
{
        // Denne partial-klassen inneholder logikken for å bygge modellen 
        // slik EF Core forventer den etter migrasjonen «UpdateProjectModel».

    [DbContext(typeof(AppDbContext))]
    [Migration("20250310202844_UpdateProjectModel")]
    partial class UpdateProjectModel
    {
        // Konfigurerer det interne EF Core ModelBuilder-objektet
        // med entiteter, kolonner, relasjoner og seed-data for denne migrasjonen.
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
        // Globale annotasjoner for EF Core-versjon og begrensning på ID-lengde
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

        // Angir standard Identity-kolonne­strategi for PostgreSQL
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        // Konfigurerer Project-entiteten:
            modelBuilder.Entity("PureLogicBackend.Models.Project", b =>
                {

        // Definerer PK-kolonnen Id med automatisk verdi­generering
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

        // Kolonner for prosjektets Title, Description og ImageUrl
                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

        // Setter Id som primærnøkkel
                    b.HasKey("Id");

        // Mapper entiteten til tabellen "Projects"
                    b.ToTable("Projects");
        // Seed-data: legger inn to standardprosjekter ved migrasjon. Disse er eldre, og kan fjernes hvis det er ønskelig
                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "I prosjektet ble byggekostnadene og klima-fotavtrykket redusert med henholdsvis 30 og 50%.",
                            ImageUrl = "/images/bjornafjorden.jpg",
                            Title = "Konseptutvikling: E39, Kryssing av Bjørnafjorden"
                        },
                        new
                        {
                            Id = 2,
                            Description = "BioZement er fortsatt under utvikling og målet er å redusere klima-fotavtrykket til betongindustrien med 20%.",
                            ImageUrl = "/images/biozement.jpg",
                            Title = "Produktutvikling av BioZement som alternativ til betong"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
