// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PureLogicBackend.Data;

#nullable disable

namespace backend.Migrations
{

    // EF Core Model Snapshot for AppDbContext – brukes internt av migreringssystemet
    // til å holde rede på den gjeldende modellen mellom migrasjoner.
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        // Bygger ModelBuilder-objektet som representerer den siste tilstanden
        // av datamodellen slik EF Core kjenner den for AppDbContext.
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Globale metadata: EF Core-versjon og maks identifikator-lengde
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            // Aktiverer PostgreSQL sin standard Identity-strategi for auto-inkrement
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Definerer konfigurasjon for Project-entiteten
            modelBuilder.Entity("PureLogicBackend.Models.Project", b =>
                {
                    // Primærnøkkel-kolonne Id med automatisk verdiøkning
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                     // Standard beskrivelse (text)
                    b.Property<string>("Description")
                        .HasColumnType("text");
                    
                    // Bilde-URL-kolonne, navngitt til snake_case i databasen
                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    // Kolonne for søkbare nøkkelord
                    b.Property<string>("Keywords")
                        .HasColumnType("text");

                    // Kolonne for detaljert (lang) beskrivelse
                    b.Property<string>("LongDescription")
                        .HasColumnType("text");

                    // Kolonne for kort beskrivelse
                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    // Tittel på prosjektet
                    b.Property<string>("Title")
                        .HasColumnType("text");

                    // Flag for synlighet på nettside
                    b.Property<bool>("VisibleOnWebsite")
                        .HasColumnType("boolean");

                    // Setter Id som primærnøkkel
                    b.HasKey("Id");

                    // Mapper entiteten til tabellen "Projects"
                    b.ToTable("Projects");

                    // Seed-data: eksempler på to prosjekter med VisibleOnWebsite = false
                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "I prosjektet ble byggekostnadene og klima-fotavtrykket redusert med henholdsvis 30 og 50%.",
                            ImageUrl = "/images/bjornafjorden.jpg",
                            Title = "Konseptutvikling: E39, Kryssing av Bjørnafjorden",
                            VisibleOnWebsite = false
                        },
                        new
                        {
                            Id = 2,
                            Description = "BioZement er fortsatt under utvikling og målet er å redusere klima-fotavtrykket til betongindustrien med 20%.",
                            ImageUrl = "/images/biozement.jpg",
                            Title = "Produktutvikling av BioZement som alternativ til betong",
                            VisibleOnWebsite = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
