name: CI/CD Pipeline for Project Upload

on:
  push:
    branches:
      - main  # Kjør denne pipelinen ved push til main-branchen

jobs:
  validate_project_data:
    runs-on: ubuntu-latest

    steps:
      # Sjekk ut koden din
      - name: Checkout code
        uses: actions/checkout@v2

      # Sett opp Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Installer nødvendige avhengigheter
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2  # Installer psycopg2 for PostgreSQL-tilkobling

      # Kjør Python-skript for å validere prosjektene
      - name: Run validation script
        run: |
          python validate_projects.py  # Kjører et Python-skript som validerer dataene
          
      # Hvis valideringen er vellykket, fortsett til opplasting
      - name: Upload project data
        if: success()
        run: |
          # Legg til steg for å laste opp dataene til produksjonsdatabasen her
          echo "Upload successful"  
