name: Deploy to Server

on:
  push:
    branches:
      - main  # Kjør pipelinen på push til main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Kjøres på Ubuntu-miljø

    steps:
      # Checker ut koden fra repositoriet
      - name: Checkout code
        uses: actions/checkout@v2

      # Setter opp SSH-nøkler for autentisering til serveren
      - name: Setup SSH keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Installerer nødvendige avhengigheter
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' 

      - name: Install dependencies
        run: |
          npm install  # Installer avhengigheter for applikasjonen

      # Steg 4: Kjør tester (valgfritt, men anbefales)
      - name: Run tests
        run: |
          npm test  # Kjør tester for å validere koden før deploy

      # Steg 5: Bygg applikasjonen (valgfritt, avhengig av prosjektet)
      - name: Build application
        run: |
          npm run build  # Kjør byggingsprosessen for applikasjonen

      # Steg 6: Deploy til serveren
      - name: Deploy to Server
        run: |
          ssh user@your-server "cd /path/to/project && git pull && npm install && pm2 restart app"
